### ISSUE TITLE
Bug: error when creating transactions for investment account

### ISSUE THREAD

**Issue by channel-42** [maybe-finance/maybe#1077]
**Describe the bug**
When trying to create a new transaction for an investment account (buy/sell), the creation errors out with ```NoMethodError (undefined method `new_record?' for nil)``` as seen in the logs below. I also noticed that the UI shows the price per share as USD, but in the logs they are processed in EUR, as defined per my app settings (see screenshot and log line 3).

I'm running [v0.1.0-alpha.14](https://github.com/maybe-finance/maybe/releases/tag/v0.1.0-alpha.14).

**To Reproduce**
1. Go to an investment account
2. Create a new transaction (e.g. buy some symbol)
3. See error

**Expected behavior**
Transaction gets created.

**Screenshots / Recordings**
<img width="467" alt="Bildschirmfoto 2024-08-10 um 14 33 45" src="https://github.com/user-attachments/assets/8be3ab65-535b-4c2f-9c87-0644d20112e2">

**Additional context**
```
I, [2024-08-10T12:43:31.749463 #1]  INFO -- : [aafe59a1-0246-4337-a855-83b0b9156fc6] Started POST "/accounts/85de865c-3adb-48c9-8c10-a0c1d0c4018c/trades" for 10.42.1.0 at 2024-08-10 12:43:31 +0000
I, [2024-08-10T12:43:31.751151 #1]  INFO -- : [aafe59a1-0246-4337-a855-83b0b9156fc6] Processing by Account::TradesController#create as TURBO_STREAM
I, [2024-08-10T12:43:31.751233 #1]  INFO -- : [aafe59a1-0246-4337-a855-83b0b9156fc6]   Parameters: {"authenticity_token"=>"[FILTERED]", "account_entry"=>{"type"=>"buy", "ticker"=>"AAPL", "date"=>"", "currency"=>"EUR", "qty"=>"10", "price"=>"100"}, "commit"=>"Add transaction", "account_id"=>"85de865c-3adb-48c9-8c10-a0c1d0c4018c"}
I, [2024-08-10T12:43:31.767641 #1]  INFO -- : [aafe59a1-0246-4337-a855-83b0b9156fc6]   Rendered layout layouts/with_sidebar.html.erb (Duration: 0.2ms | GC: 0.0ms)
I, [2024-08-10T12:43:31.767776 #1]  INFO -- : [aafe59a1-0246-4337-a855-83b0b9156fc6] Completed 500 Internal Server Error in 16ms (ActiveRecord: 1.3ms (3 queries, 0 cached) | GC: 0.0ms)
E, [2024-08-10T12:43:31.769864 #1] ERROR -- : [aafe59a1-0246-4337-a855-83b0b9156fc6]   
[aafe59a1-0246-4337-a855-83b0b9156fc6] ActionView::Template::Error (undefined method `new_record?' for nil):
[aafe59a1-0246-4337-a855-83b0b9156fc6] 
Causes:
[aafe59a1-0246-4337-a855-83b0b9156fc6] NoMethodError (undefined method `new_record?' for nil)
[aafe59a1-0246-4337-a855-83b0b9156fc6]     2: 
[aafe59a1-0246-4337-a855-83b0b9156fc6]     3: <%= styled_form_with data: { turbo_frame: "_top" },
[aafe59a1-0246-4337-a855-83b0b9156fc6]     4:                      scope: :account_entry,
[aafe59a1-0246-4337-a855-83b0b9156fc6]     5:                      url: entry.new_record? ? account_trades_path(entry.account) : account_entry_path(entry.account, entry) do |form| %>
[aafe59a1-0246-4337-a855-83b0b9156fc6]     6:   <div class="space-y-4">
[aafe59a1-0246-4337-a855-83b0b9156fc6]     7:     <div class="space-y-2">
[aafe59a1-0246-4337-a855-83b0b9156fc6]     8:       <%= form.select :type, options_for_select([%w[Buy buy], %w[Sell sell]], "buy"), label: t(".type") %>
[aafe59a1-0246-4337-a855-83b0b9156fc6]   
[aafe59a1-0246-4337-a855-83b0b9156fc6] app/views/account/trades/_form.html.erb:5
[aafe59a1-0246-4337-a855-83b0b9156fc6] app/views/account/trades/new.html.erb:2
[aafe59a1-0246-4337-a855-83b0b9156fc6] app/helpers/forms_helper.rb:8:in `modal_form_wrapper'
[aafe59a1-0246-4337-a855-83b0b9156fc6] app/views/account/trades/new.html.erb:1
[aafe59a1-0246-4337-a855-83b0b9156fc6] app/controllers/account/trades_controller.rb:21:in `create'                                               
```

**Comment by zachgoll** [comment]
@channel-42 thanks for the info, will take a look!

**Comment by zachgoll** [comment]
@channel-42 I'm not able to reproduce this error on the latest version of Maybe.

Can you provide me the exact form that you're submitting that causes this error?  I've tried quite a few combinations without any luck.

**Comment by zachgoll** [comment]
@channel-42 another thing to check—have you set up the Synth API for fetching security prices?

**Comment by channel-42** [comment]
@zachgoll Synth API is set up and working. Any form produces the error on my end (updated to [v0.1.0-alpha.15](https://github.com/maybe-finance/maybe/releases/tag/v0.1.0-alpha.15)), even when using the example values:
![Bildschirmfoto 2024-08-18 um 17 52 03](https://github.com/user-attachments/assets/302d8eaa-ee8f-4078-8510-190d58a887ec)

But I think I found the issue: the logs do not show the “default date” (i.e. the date that is show when opening the form):
```
INFO -- : [04c43608-8fc6-40ac-ab5a-5a7b76bba631]   Parameters: {"authenticity_token"=>"[FILTERED]", "account_entry"=>{"type"=>"buy", "ticker"=>"AAPL", "date"=>"",  │
│ "amount"=>"", "transfer_account_id"=>"", "qty"=>"10", "price"=>"100"}, "commit"=>"Add transaction", "account_id"=>"xxxxxxxxxxxxxxxx"}
```

After I manually entered a date, the transaction is added successfully and the logs now show the date:
```
INFO -- : [04c43608-8fc6-40ac-ab5a-5a7b76bba631]   Parameters: {"authenticity_token"=>"[FILTERED]", "account_entry"=>{"type"=>"buy", "ticker"=>"AAPL", "date"=>"2024-08-18",  │
│ "amount"=>"", "transfer_account_id"=>"", "qty"=>"10", "price"=>"100"}, "commit"=>"Add transaction", "account_id"=>"xxxxxxxxxxxxxxxx"}
```

**Comment by zachgoll** [comment]
@channel-42 ahh that is interesting.  The date shows up in the params when I submit, but I'm using a different date format.  I'm wondering if the parsing step may be the issue here:
![CleanShot 2024-08-20 at 14 16 25@2x](https://github.com/user-attachments/assets/05638169-2861-4eb9-9dcd-766d0e2dd838)

**Comment by zachgoll** [comment]
@channel-42 I've been looking into this and cannot get this reproduced.

What's odd to me is that you're getting "default" values with this form.  There should not be any default values when initializing this form.

When you open the form (as shown in the video below), what is different for you?

https://github.com/user-attachments/assets/f4c8bc65-31f6-4627-b4e7-477d0687c570

**Comment by zachgoll** [comment]
Going to close due to inactivity.  Happy to re-open later if needed!
