### ISSUE TITLE
Bug: Unable to run locally through Devcontainer

### ISSUE THREAD

**Issue by itsDxdot** [maybe-finance/maybe#1193]
**Describe the bug**
I attempted to run the project following these steps:

**To Reproduce**
1. Cloned the project repository using `git clone`
2. Opened the project in VSCode and successfully executed "Reopen in Container"
3. Ran the following commands in order:
   ```
   cp .env.example .env
   bin/setup
   bin/dev
   ```
4. Encountered an error when running `bin/dev`

**Screenshots / Recordings**

```
06:19:18 worker.1 |  ["/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:69:in `rescue in new_client'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:57:in `new_client'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:982:in `connect'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:994:in `reconnect'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:662:in `block in reconnect!'", "/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:661:in `reconnect!'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:763:in `block in verify!'", "/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:754:in `verify!'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:771:in `connect!'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:977:in `block in with_raw_connection'", "/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:976:in `with_raw_connection'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/postgresql/quoting.rb:128:in `quote_string'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/quoting.rb:76:in `quote'", "/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/postgresql/quoting.rb:122:in `quote'", "/bundle/ruby/3.3.0/gems/good_job-4.3.0/lib/good_job/notifier.rb:261:in `with_connection'", "/bundle/ruby/3.3.0/gems/good_job-4.3.0/lib/good_job/notifier.rb:204:in `block in create_listen_task'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in `process_task'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/timer_set.rb:166:in `block (2 levels) in process_tasks'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'", "<internal:kernel>:187:in `loop'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'", "/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'"]
^C06:19:20 system   | SIGINT received, starting shutdown
06:19:20 web.1    | - Gracefully stopping, waiting for requests to finish
06:19:20 web.1    | === puma shutdown: 2024-09-20 06:19:20 +0000 ===
06:19:20 web.1    | - Goodbye!
06:19:20 web.1    | Exiting
06:19:20 system   | sending SIGTERM to all processes
06:19:20 web.1    | terminated by SIGINT
06:19:20 css.1    | exited with code 0
06:19:21 worker.1 | [GoodJob] GoodJob error: ActiveRecord::ConnectionNotEstablished: could not connect to server: Connection refused
06:19:21 worker.1 |     Is the server running on host "::1" and accepting
06:19:21 worker.1 |     TCP/IP connections on port 5432?
06:19:21 worker.1 | could not connect to server: Connection refused
06:19:21 worker.1 |     Is the server running on host "127.0.0.1" and accepting
06:19:21 worker.1 |     TCP/IP connections on port 5432?
```

![image](https://github.com/user-attachments/assets/6b39efe3-ab49-4f4a-8e15-685da8abb758)

![image](https://github.com/user-attachments/assets/9bec1059-1123-4dce-8685-e07d08bd9b67)

**Comment by jestinjoshi** [comment]
Have you filled in the necessary details in `.env` file?

Please check if you have the database configuration set up properly.

**Comment by DxPoly** [comment]
Thank.
I will re-confirm the entire process in the next few days to ensure it is complete, and if there are any updates, I will reply here

**Comment by zachgoll** [comment]
@DxPoly it looks like your database is not running on the standard `5432` port and the server is not able to connect.

I'm going to convert this to a Discussion as this is not a bug with the app itself.

If you continue to have troubles with Devcontainers, I'd recommend trying to set this up locally following one of our [setup guides](https://github.com/maybe-finance/maybe/wiki/Mac-Dev-Setup-Guide).
