### ISSUE TITLE
Changing currency on new profile page caused fatal error

### ISSUE THREAD

**Issue by karanj** [maybe-finance/maybe#564]
Since my base currency is AUD, I went to the settings page to change it to AUD after creating a couple of sample accounts and realising I had to select AUD every time. Whole thing bailed on me - here's the error stack:

<header>
  <h1>
    NameError
      in SettingsController#update
  </h1>
</header>

<main role="main" id="container">
    <div class="exception-message">
    <div class="message">uninitialized constant SettingsController::ConvertCurrencyJob</div>
  </div>

    <div class="source " id="frame-source-0-0">
      <div class="info">
        Extracted source (around line <strong>#17</strong>):
      </div>
      <div class="data">
        
15 16 17 18 19 20 | # If the family attribute for currency is changed, we need to convert all account balances to the new currency with the ConvertCurrencyJob job     if user_params_with_family[:family_attributes][:currency] != Current.family.currency       ConvertCurrencyJob.perform_later(Current.family)     end      if Current.user.update(user_params_with_family)
-- | --
      </div>
    </div>
   <p><code>Rails.root: /workspace</code></p>

<div id="traces-0">
    <a href="http://localhost:3003/settings/edit#" onclick="hide('Framework-Trace-0');hide('Full-Trace-0');show('Application-Trace-0');; return false;">Application Trace</a> |
    <a href="http://localhost:3003/settings/edit#" onclick="hide('Application-Trace-0');hide('Full-Trace-0');show('Framework-Trace-0');; return false;">Framework Trace</a> |
    <a href="http://localhost:3003/settings/edit#" onclick="hide('Application-Trace-0');hide('Framework-Trace-0');show('Full-Trace-0');; return false;">Full Trace</a> 
 
    <div id="Full-Trace-0" style="display: block;">
      <code class="traces">
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="0" href="http://localhost:3003/settings/edit#">
            app/controllers/settings_controller.rb:17:in `update'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="1" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_controller/metal/basic_implicit_render.rb:8:in `send_action'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="2" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/abstract_controller/base.rb:226:in `process_action'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="3" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_controller/metal/rendering.rb:193:in `process_action'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="4" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/abstract_controller/callbacks.rb:261:in `block in process_action'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="5" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="6" href="http://localhost:3003/settings/edit#">
            turbo-rails (2.0.5) lib/turbo-rails.rb:24:in `with_request_id'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="7" href="http://localhost:3003/settings/edit#">
            turbo-rails (2.0.5) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="8" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="9" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actiontext/lib/action_text/rendering.rb:25:in `with_renderer'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="10" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actiontext/lib/action_text/engine.rb:71:in `block (4 levels) in &lt;class:Engine&gt;'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="11" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:130:in `instance_exec'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="12" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="13" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:141:in `run_callbacks'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="14" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/abstract_controller/callbacks.rb:260:in `process_action'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="15" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_controller/metal/rescue.rb:27:in `process_action'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="16" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_controller/metal/instrumentation.rb:77:in `block in process_action'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="17" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activesupport/lib/active_support/notifications.rb:210:in `block in instrument'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="18" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="19" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activesupport/lib/active_support/notifications.rb:210:in `instrument'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="20" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_controller/metal/instrumentation.rb:76:in `process_action'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="21" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="22" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activerecord/lib/active_record/railties/controller_runtime.rb:32:in `process_action'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="23" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/abstract_controller/base.rb:163:in `process'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="24" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionview/lib/action_view/rendering.rb:40:in `process'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="25" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_controller/metal.rb:227:in `dispatch'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="26" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_controller/metal.rb:310:in `dispatch'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="27" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="28" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/routing/route_set.rb:33:in `serve'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="29" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/journey/router.rb:53:in `block in serve'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="30" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/journey/router.rb:133:in `block in find_routes'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="31" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/journey/router.rb:126:in `each'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="32" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/journey/router.rb:126:in `find_routes'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="33" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/journey/router.rb:34:in `serve'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="34" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/routing/route_set.rb:879:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="35" href="http://localhost:3003/settings/edit#">
            rack (3.0.9.1) lib/rack/tempfile_reaper.rb:20:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="36" href="http://localhost:3003/settings/edit#">
            rack (3.0.9.1) lib/rack/etag.rb:29:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="37" href="http://localhost:3003/settings/edit#">
            rack (3.0.9.1) lib/rack/conditional_get.rb:43:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="38" href="http://localhost:3003/settings/edit#">
            rack (3.0.9.1) lib/rack/head.rb:15:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="39" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="40" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="41" href="http://localhost:3003/settings/edit#">
            rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="42" href="http://localhost:3003/settings/edit#">
            rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="43" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/cookies.rb:704:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="44" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activerecord/lib/active_record/migration.rb:674:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="45" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="46" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:101:in `run_callbacks'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="47" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/callbacks.rb:30:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="48" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/executor.rb:16:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="49" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="50" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="51" href="http://localhost:3003/settings/edit#">
            web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="52" href="http://localhost:3003/settings/edit#">
            web-console (4.2.1) lib/web_console/middleware.rb:19:in `block in call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="53" href="http://localhost:3003/settings/edit#">
            web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="54" href="http://localhost:3003/settings/edit#">
            web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="55" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="56" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) railties/lib/rails/rack/logger.rb:41:in `call_app'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="57" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) railties/lib/rails/rack/logger.rb:29:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="58" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="59" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/request_id.rb:33:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="60" href="http://localhost:3003/settings/edit#">
            rack (3.0.9.1) lib/rack/method_override.rb:28:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="61" href="http://localhost:3003/settings/edit#">
            rack (3.0.9.1) lib/rack/runtime.rb:24:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="62" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="63" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="64" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="65" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/server_timing.rb:60:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="66" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/executor.rb:16:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="67" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) actionpack/lib/action_dispatch/middleware/static.rb:27:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="68" href="http://localhost:3003/settings/edit#">
            rack (3.0.9.1) lib/rack/sendfile.rb:114:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="69" href="http://localhost:3003/settings/edit#">
            rails (5411787a155e) railties/lib/rails/engine.rb:536:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="70" href="http://localhost:3003/settings/edit#">
            puma (6.4.2) lib/puma/configuration.rb:272:in `call'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="71" href="http://localhost:3003/settings/edit#">
            puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="72" href="http://localhost:3003/settings/edit#">
            puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="73" href="http://localhost:3003/settings/edit#">
            puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="74" href="http://localhost:3003/settings/edit#">
            puma (6.4.2) lib/puma/server.rb:464:in `process_client'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="75" href="http://localhost:3003/settings/edit#">
            puma (6.4.2) lib/puma/server.rb:245:in `block in run'
          </a>
          <br>
          <a class="trace-frames trace-frames-0" data-exception-object-id="34680" data-frame-id="76" href="http://localhost:3003/settings/edit#">
            puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
          </a>
          <br>
      </code>
    </div>

  
</div>

  <h2 class="request-heading">Request</h2>
  <p><b>Parameters</b>:</p> <pre>{"_method"=&gt;"patch",
 "authenticity_token"=&gt;"[FILTERED]",
 "user"=&gt;{"family_attributes"=&gt;{"name"=&gt;"Juneja", "currency"=&gt;"AUD"}, "first_name"=&gt;"Karan", "last_name"=&gt;"", "email"=&gt;"[FILTERED]", "password"=&gt;"[FILTERED]", "password_confirmation"=&gt;"[FILTERED]"}}
</pre></main>NameError in SettingsController#update
uninitialized constant SettingsController::ConvertCurrencyJob
Extracted source (around line #17):

15
16
17
18
19
20
              

	

    # If the family attribute for currency is changed, we need to convert all account balances to the new currency with the ConvertCurrencyJob job
    if user_params_with_family[:family_attributes][:currency] != Current.family.currency
      ConvertCurrencyJob.perform_later(Current.family)
    end

    if Current.user.update(user_params_with_family)

Rails.root: /workspace
[Application Trace](http://localhost:3003/settings/edit#) | [Framework Trace](http://localhost:3003/settings/edit#) | [Full Trace](http://localhost:3003/settings/edit#)
app/controllers/settings_controller.rb:17:in `update'
rails (5411787a155e) actionpack/lib/action_controller/metal/basic_implicit_render.rb:8:in `send_action'
rails (5411787a155e) actionpack/lib/abstract_controller/base.rb:226:in `process_action'
rails (5411787a155e) actionpack/lib/action_controller/metal/rendering.rb:193:in `process_action'
rails (5411787a155e) actionpack/lib/abstract_controller/callbacks.rb:261:in `block in process_action'
rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
turbo-rails (2.0.5) lib/turbo-rails.rb:24:in `with_request_id'
turbo-rails (2.0.5) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
rails (5411787a155e) actiontext/lib/action_text/rendering.rb:25:in `with_renderer'
rails (5411787a155e) actiontext/lib/action_text/engine.rb:71:in `block (4 levels) in <class:Engine>'
rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:130:in `instance_exec'
rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:141:in `run_callbacks'
rails (5411787a155e) actionpack/lib/abstract_controller/callbacks.rb:260:in `process_action'
rails (5411787a155e) actionpack/lib/action_controller/metal/rescue.rb:27:in `process_action'
rails (5411787a155e) actionpack/lib/action_controller/metal/instrumentation.rb:77:in `block in process_action'
rails (5411787a155e) activesupport/lib/active_support/notifications.rb:210:in `block in instrument'
rails (5411787a155e) activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
rails (5411787a155e) activesupport/lib/active_support/notifications.rb:210:in `instrument'
rails (5411787a155e) actionpack/lib/action_controller/metal/instrumentation.rb:76:in `process_action'
rails (5411787a155e) actionpack/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
rails (5411787a155e) activerecord/lib/active_record/railties/controller_runtime.rb:32:in `process_action'
rails (5411787a155e) actionpack/lib/abstract_controller/base.rb:163:in `process'
rails (5411787a155e) actionview/lib/action_view/rendering.rb:40:in `process'
rails (5411787a155e) actionpack/lib/action_controller/metal.rb:227:in `dispatch'
rails (5411787a155e) actionpack/lib/action_controller/metal.rb:310:in `dispatch'
rails (5411787a155e) actionpack/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
rails (5411787a155e) actionpack/lib/action_dispatch/routing/route_set.rb:33:in `serve'
rails (5411787a155e) actionpack/lib/action_dispatch/journey/router.rb:53:in `block in serve'
rails (5411787a155e) actionpack/lib/action_dispatch/journey/router.rb:133:in `block in find_routes'
rails (5411787a155e) actionpack/lib/action_dispatch/journey/router.rb:126:in `each'
rails (5411787a155e) actionpack/lib/action_dispatch/journey/router.rb:126:in `find_routes'
rails (5411787a155e) actionpack/lib/action_dispatch/journey/router.rb:34:in `serve'
rails (5411787a155e) actionpack/lib/action_dispatch/routing/route_set.rb:879:in `call'
rack (3.0.9.1) lib/rack/tempfile_reaper.rb:20:in `call'
rack (3.0.9.1) lib/rack/etag.rb:29:in `call'
rack (3.0.9.1) lib/rack/conditional_get.rb:43:in `call'
rack (3.0.9.1) lib/rack/head.rb:15:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/cookies.rb:704:in `call'
rails (5411787a155e) activerecord/lib/active_record/migration.rb:674:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'
rails (5411787a155e) activesupport/lib/active_support/callbacks.rb:101:in `run_callbacks'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/callbacks.rb:30:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/executor.rb:16:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'
web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.1) lib/web_console/middleware.rb:19:in `block in call'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'
rails (5411787a155e) railties/lib/rails/rack/logger.rb:41:in `call_app'
rails (5411787a155e) railties/lib/rails/rack/logger.rb:29:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/request_id.rb:33:in `call'
rack (3.0.9.1) lib/rack/method_override.rb:28:in `call'
rack (3.0.9.1) lib/rack/runtime.rb:24:in `call'
rails (5411787a155e) activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/server_timing.rb:60:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/executor.rb:16:in `call'
rails (5411787a155e) actionpack/lib/action_dispatch/middleware/static.rb:27:in `call'
rack (3.0.9.1) lib/rack/sendfile.rb:114:in `call'
rails (5411787a155e) railties/lib/rails/engine.rb:536:in `call'
puma (6.4.2) lib/puma/configuration.rb:272:in `call'
puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
puma (6.4.2) lib/puma/server.rb:464:in `process_client'
puma (6.4.2) lib/puma/server.rb:245:in `block in run'
puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
Request

Parameters:

{"_method"=>"patch",
 "authenticity_token"=>"[FILTERED]",
 "user"=>{"family_attributes"=>{"name"=>"J", "currency"=>"AUD"}, "first_name"=>"Karan", "last_name"=>"", "email"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}

**Comment by giubaru** [comment]
@zachgoll Hey! Something happened here: https://github.com/maybe-finance/maybe/blob/110855d077a0a501674d5866fe43844df93c3159/app/controllers/settings_controller.rb#L17


Seems that the Jobs were deleted in the PR #543

**Comment by zachgoll** [comment]
@giubaru yes, good catch, this is definitely a bug.  The job removal was intended, but leaving the call to it was not.

**Comment by zachgoll** [comment]
@karanj the bug itself is fixed now.  We're still pretty early with the multi-currency implementation, so if you change your family setting to `AUD`, you may still need to change existing accounts you had created.

Edit/delete functionality is not in the UI yet for this, so your best bet is a direct DB change for now.  That functionality will be in soon though!

**Comment by karanj** [comment]
@zachgoll thanks for the speedy resolution, I'll check it out.

for what it's worth - I had created two accounts which I'd already marked as AUD. So it was rather that I was updating my default; conversion was not intended.
