### ISSUE TITLE
Bundle install fails on Windows due to ECONNRESET

### ISSUE THREAD

**Issue by pronoym99** [maybe-finance/maybe#765]
My Windows setup fails after running `bin/setup`. 

```
<Errno:: ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect (https://rubygems.org/specs.4.8.gz)>
```

**Comment by zachgoll** [comment]
@pronoym99 can you please provide more details about your local environment? (version numbers, OS, etc.)

**Comment by pronoym99** [comment]
**OS and system details**

Edition - Windows 11 Pro
Version - 21H2
OS build - 22000.2538
Processor - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
System type - 64-bit operating system, x64-based processor

**Other details**
ruby version - ruby 3.3.1 (2024-04-23 revision c56cd86388) [x64-mingw-ucrt]
Postgres - v16.3

**Comment by pronoym99** [comment]
No, I am not behind a proxy and I am not using WSL. I get the same error on running the `update` command.

```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect (Gem::RemoteFetcher::FetchError)
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/remote_fetcher.rb:266:in `rescue in fetch_path'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/remote_fetcher.rb:246:in `fetch_path'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/remote_fetcher.rb:294:in `cache_update_path'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/source.rb:190:in `load_specs'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/spec_fetcher.rb:253:in `tuples_for'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/spec_fetcher.rb:220:in `block in available_specs'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/source_list.rb:94:in `each'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/source_list.rb:94:in `each_source'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/spec_fetcher.rb:215:in `available_specs'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/spec_fetcher.rb:91:in `search_for_dependency'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/commands/update_command.rb:143:in `fetch_remote_gems'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/commands/update_command.rb:168:in `highest_remote_name_tuple'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/commands/update_command.rb:233:in `rubygems_target_version'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/commands/update_command.rb:278:in `update_rubygems'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/commands/update_command.rb:99:in `execute'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/command.rb:326:in `invoke_with_build_args'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/command_manager.rb:255:in `invoke_command'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/command_manager.rb:194:in `process_args'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/command_manager.rb:152:in `run'
        F:/Ruby33-x64/lib/ruby/3.3.0/rubygems/gem_runner.rb:56:in `run'
        F:/Ruby33-x64/bin/gem.cmd:20:in `<main>'```

**Comment by flacnut** [comment]
You can try manually changing the URL at the top of the `Gemfile` to be non-HTTPS

```
~/maybe$ cat Gemfile
source "https://rubygems.org"    <-- Change this

ruby file: ".ruby-version"
....
```

**Comment by zachgoll** [comment]
Yep, I agree that this is not specific to Maybe.  

@pronoym99 the easiest and preferred way to run this project is with WSL, which we've provided some instructions for in our setup guide:

https://github.com/maybe-finance/maybe/wiki/Windows-Dev-Setup-Guide

If you have any issues with the provided guide, just leave a comment here, but I'm going to close this issue out for now.
